import React, { useState } from 'react';
import { MoreHorizontal } from 'lucide-react';
import { Drawer, DrawerContent, DrawerHeader, DrawerTitle, DrawerDescription } from '@/components/ui/drawer';
import { equipmentPool } from '@/lib/training/exerciseSelection';
export default function ExerciseOptions({ exercise, workoutExercise, allExercises, profile, canReplace, onReplace, onSkip, onDetails }) {
  const [open,setOpen]=useState(false),[replacing,setReplacing]=useState(false);
  const allowed=equipmentPool(profile||{}),alternatives=allExercises.filter(e=>e.id!==exercise?.id&&e.primaryMuscle===exercise?.primaryMuscle&&e.category===exercise?.category&&(!allowed||allowed.has(e.equipment)));
  const close=()=>{setOpen(false);setReplacing(false)};
  return <><button aria-label={`Options for ${workoutExercise.exerciseName}`} onClick={()=>setOpen(true)} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-secondary"><MoreHorizontal className="h-5 w-5"/></button><Drawer open={open} onOpenChange={value=>value?setOpen(true):close()}><DrawerContent className="bg-card text-foreground"><div className="mx-auto w-full max-w-md px-5 pb-8"><DrawerHeader className="px-0"><DrawerTitle>{replacing?'Replace exercise':workoutExercise.exerciseName}</DrawerTitle><DrawerDescription>{replacing?'Same primary muscle and movement category, using your equipment.':'Changes affect this workout, not your program.'}</DrawerDescription></DrawerHeader>{replacing?<div className="max-h-[50dvh] space-y-2 overflow-y-auto">{alternatives.length?alternatives.map(e=><button key={e.id} onClick={()=>{onReplace(e);close()}} className="w-full rounded-xl bg-secondary p-4 text-left"><b className="text-sm">{e.name}</b><p className="mt-1 text-xs text-muted-foreground">{e.equipment}</p></button>):<p className="py-5 text-sm text-muted-foreground">No suitable replacements in your library for this equipment.</p>}<button onClick={()=>setReplacing(false)} className="h-12 w-full text-sm font-bold">Back</button></div>:<div className="space-y-2"><button onClick={()=>{close();onDetails()}} className="h-12 w-full rounded-xl bg-secondary font-semibold">Exercise details</button><button disabled={!canReplace} onClick={()=>setReplacing(true)} className="h-12 w-full rounded-xl bg-secondary font-semibold disabled:opacity-40">Replace exercise</button>{!canReplace&&<p className="text-xs text-muted-foreground">Replacement is available before you save any sets for this exercise.</p>}<button onClick={()=>{onSkip();close()}} className="h-12 w-full rounded-xl bg-secondary font-semibold">{workoutExercise.skipped?'Restore exercise':'Skip remaining sets'}</button></div>}</div></DrawerContent></Drawer></>;
}