import React, { useState } from 'react';
import { Trash2 } from 'lucide-react';
import SetRow from '@/components/workout/SetRow';
import ExerciseOptions from '@/components/workout/ExerciseOptions';
import ExerciseDetails from '@/components/workout/ExerciseDetails';
import { suggestProgression } from '@/lib/training/e1rm';
export default function ExerciseCard({ workoutExercise, exercise, rows, previousSets=[], onEdit, onToggle, onAddSet, onRemoveSet, savingIds, allExercises, profile, plan, onReplace, onSkip }) {
  const [details,setDetails]=useState(false),locked=plan?.structureLocked||plan?.athleteMode==='track_only'||workoutExercise.coachMandated,suggestion=locked?null:suggestProgression(previousSets,workoutExercise.repMin,workoutExercise.repMax);
  return <section className={`limit-surface mt-5 rounded-[2rem] p-5 transition-opacity ${workoutExercise.skipped?'opacity-55':''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-heading text-lg font-extrabold tracking-tight">{workoutExercise.exerciseName}</h2><p className="mt-1 text-xs text-muted-foreground">{exercise?.primaryMuscle || workoutExercise.primaryMuscle || 'Other'} · {exercise?.category || workoutExercise.category || 'Exercise'} · {workoutExercise.repMin}–{workoutExercise.repMax} reps</p></div><ExerciseOptions exercise={exercise} workoutExercise={workoutExercise} allExercises={allExercises} profile={profile} canReplace={!rows.some(r=>r.savedId||r.pending)} locked={locked} onReplace={onReplace} onSkip={onSkip} onDetails={()=>setDetails(true)}/></div>{workoutExercise.skipped?<button onClick={onSkip} className="mt-4 h-11 w-full rounded-xl bg-secondary text-sm font-bold">Restore exercise</button>:<><div className="mt-3 grid grid-cols-2 divide-x divide-border rounded-xl bg-secondary/45 py-2"><div className="px-3"><p className="text-[9px] font-bold uppercase tracking-wider text-muted-foreground">Last</p><p className="mt-1 truncate text-sm font-bold tabular-nums">{previousSets.length?`${previousSets[0].weight} × ${previousSets[0].reps}`:'First session'}</p></div><div className="px-3"><p className="text-[9px] font-bold uppercase tracking-wider text-primary">Target</p><p className="mt-1 truncate text-sm font-bold tabular-nums">{suggestion?`${suggestion.weight} lb · ${workoutExercise.repMin}–${workoutExercise.repMax}`:`${workoutExercise.repMin}–${workoutExercise.repMax} reps`}</p></div></div>{suggestion&&<p className="mt-2 text-xs text-muted-foreground">{suggestion.note}</p>}<div className="mt-4 grid grid-cols-[20px_54px_minmax(0,1fr)_minmax(0,1fr)_36px_40px] gap-2 text-center text-[9px] font-bold uppercase tracking-wider text-muted-foreground"><span>Set</span><span>Prev</span><span>Lb</span><span>Reps</span><span>RIR</span><span/></div>{rows.map((row,index)=><div key={row.key} className="relative"><SetRow row={row} previous={previousSets[row.setNumber-1]||previousSets.at(-1)} saving={savingIds.has(row.key)} onEdit={(k,v)=>onEdit(row.key,k,v)} onToggle={()=>onToggle(row.key)}/>{index>=workoutExercise.sets&&!row.savedId&&!row.pending&&<button aria-label={`Delete set ${row.setNumber}`} onClick={()=>onRemoveSet(row.key)} className="absolute -right-2 -top-1 grid h-6 w-6 place-items-center rounded-full bg-secondary text-muted-foreground"><Trash2 className="h-3 w-3"/></button>}</div>)}{!locked&&<button onClick={onAddSet} disabled={rows.length>=30} className="mt-4 min-h-11 w-full rounded-xl border border-dashed border-border/70 bg-secondary/30 text-xs font-black tracking-wide text-muted-foreground transition-colors active:bg-secondary disabled:opacity-40">+ ADD SET</button>}</>}<ExerciseDetails exercise={exercise} open={details} onOpenChange={setDetails}/></section>;
}