import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import {blankRegimen,loadImportedPlan,matchRegimen,parseRegimen,saveImportedRegimen} from '@/lib/training/importRegimen';
export default function useRegimenImport(planId){
  const client=useQueryClient(),catalog=useQuery({queryKey:['exercises'],queryFn:()=>base44.entities.Exercise.list(null,500),staleTime:60000}),[stage,setStage]=useState('source'),[draft,setDraft]=useState(),[meta,setMeta]=useState({sport:'',seasonPhase:'not_applicable',coachProvided:false,athleteMode:'smart_progression',structureLocked:false}),[sourceType,setSourceType]=useState('pasted_text'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(!planId||!catalog.data)return;setBusy(true);loadImportedPlan(planId,catalog.data).then(result=>{setDraft(result.draft);setMeta(result.meta);setSourceType(result.plan.sourceType||'manual');setStage('review')}).catch(e=>setError(e.message||'Couldn’t load this plan.')).finally(()=>setBusy(false))},[planId,catalog.data]);
  const begin=async({text,file,type})=>{setBusy(true);setError('');try{const parsed=type==='manual'?blankRegimen():await parseRegimen({text,file});setDraft(matchRegimen(parsed,catalog.data||[]));setSourceType(type);setStage('review')}catch(e){setError(e.message||'LIMIT couldn’t read that regimen. Try pasted text or another file.')}finally{setBusy(false)}};
  const day=(index,patch)=>setDraft(value=>({...value,days:value.days.map((item,i)=>i===index?{...item,...patch}:item)})),exercise=(dayIndex,index,patch)=>setDraft(value=>({...value,days:value.days.map((item,i)=>i===dayIndex?{...item,exercises:item.exercises.map((row,j)=>j===index?{...row,...patch}:row)}:item)})),addDay=()=>setDraft(value=>({...value,days:[...value.days,{key:crypto.randomUUID(),name:`Day ${value.days.length+1}`,weekday:[0,1,2,3,4,5,6].find(number=>!value.days.some(item=>item.weekday===number))??0,exercises:[]}]})),removeDay=index=>setDraft(value=>({...value,days:value.days.filter((_,i)=>i!==index)})),addExercise=index=>setDraft(value=>({...value,days:value.days.map((item,i)=>i===index?{...item,exercises:[...item.exercises,{key:crypto.randomUUID(),importedName:'New exercise',exerciseName:'New exercise',sets:3,repMin:8,repMax:12,restSeconds:120,candidates:[]}]}:item)})),removeExercise=(dayIndex,index)=>setDraft(value=>({...value,days:value.days.map((item,i)=>i===dayIndex?{...item,exercises:item.exercises.filter((_,j)=>j!==index)}:item)}));
  const save=async duplicate=>{setBusy(true);setError('');try{await saveImportedRegimen(draft,meta,{sourceType,existingId:planId,duplicate});await Promise.all([client.invalidateQueries({queryKey:['activePlan']}),client.invalidateQueries({queryKey:['workoutExercises']})]);setStage('done')}catch(e){setError(e.message||'Couldn’t save this program. Try again.')}finally{setBusy(false)}};
  return{stage,setStage,draft,setDraft,meta,setMeta,busy:busy||catalog.isLoading,error,begin,day,exercise,addDay,removeDay,addExercise,removeExercise,save,catalog:catalog.data||[],editing:!!planId};
}