import React from 'react';
import {useQuery} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import {today,sumMacros} from '@/components/limit/data';
import {calculateMuscleRating,emptyRating} from '@/components/limit/muscleRating';
import {profileWeightLb} from '@/components/limit/nutritionTargets';
import HomeWorkout from '@/components/limit/HomeWorkout';
import MacroCard from '@/components/limit/MacroCard';
import MuscleRatingPreview from '@/components/limit/MuscleRatingPreview';
import PullToRefresh from '@/components/limit/PullToRefresh';
export default function Home(){const date=today();const profile=useQuery({queryKey:['userProfile'],queryFn:()=>base44.entities.UserProfile.list(),staleTime:30000}),foodsQuery=useQuery({queryKey:['foodEntries',date],queryFn:()=>base44.entities.FoodEntry.filter({date}),staleTime:30000}),daysQuery=useQuery({queryKey:['workoutDays'],queryFn:()=>base44.entities.WorkoutDay.list('weekday'),staleTime:30000}),weightsQuery=useQuery({queryKey:['weightEntries'],queryFn:()=>base44.entities.WeightEntry.list('date',30),staleTime:30000}),workoutExercises=useQuery({queryKey:['workoutExercises'],queryFn:()=>base44.entities.WorkoutExercise.list(),staleTime:30000}),ratingData=useQuery({queryKey:['muscleRatingData'],queryFn:async()=>{const[sets,exercises,sessions]=await Promise.all([base44.entities.ExerciseSet.list('-timestamp',500),base44.entities.Exercise.list(),base44.entities.WorkoutSession.list('-date',100)]);return{sets,exercises,sessions}},staleTime:30000});const p=profile.data?.[0]||{},foods=foodsQuery.data||[],days=daysQuery.data||[],weights=weightsQuery.data||[],data=ratingData.data,rating=data?calculateMuscleRating({...data,profile:p,weights}):emptyRating(),m=sumMacros(foods),weekday=(new Date().getDay()+6)%7,day=days.find(x=>x.weekday===weekday),count=(workoutExercises.data||[]).filter(x=>x.workoutDayId===day?.id).length;const refresh=()=>Promise.all([profile.refetch(),foodsQuery.refetch(),daysQuery.refetch(),weightsQuery.refetch(),workoutExercises.refetch(),ratingData.refetch()]);return <PullToRefresh onRefresh={refresh}><div><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-500">{new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(new Date())}</p><h1 className="mt-2 text-3xl font-black tracking-tight">Ready, {p.name?.split(' ')[0]||'athlete'}?</h1></header><HomeWorkout day={day} exerciseCount={count}/><h2 className="mb-3 mt-7 text-sm font-black tracking-[.16em] text-zinc-400">NUTRITION</h2><div className="grid grid-cols-2 gap-3"><MacroCard label="CALORIES" value={m.calories} goal={p.calorieTarget||2200} unit=""/><MacroCard label="PROTEIN" value={m.protein} goal={p.proteinTarget||150}/><MacroCard label="Carbs" value={m.carbs} goal={p.carbTarget||250} color="bg-blue-500"/><MacroCard label="Fat" value={m.fat} goal={p.fatTarget||70} color="bg-blue-400"/></div><MuscleRatingPreview rating={rating}/><section className="mt-7 rounded-2xl border border-zinc-800 bg-[#121217] p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-zinc-500">Progress snapshot</p><div className="mt-3 flex items-end justify-between"><div><b className="text-3xl">{weights.at(-1)?Math.round((weights.at(-1).unit==='kg'?weights.at(-1).weight*2.20462:weights.at(-1).weight)*10)/10:Math.round(profileWeightLb(p)*10)/10||'—'}</b><span className="ml-1 text-sm text-zinc-500">lb</span></div><p className="text-sm text-zinc-500">Goal {p.goalWeight||'—'}</p></div></section></div></PullToRefresh>}