import React,{Fragment,useId} from 'react';
import {BODY_VIEW_BOX,detailLines,headPath,regions,silhouette} from '@/components/limit/athleticBodyArtwork';
const tiers={Beginner:{color:'#10b981',deep:'#064e3b',edge:'#6ee7b7',glow:.2},Intermediate:{color:'#2563eb',deep:'#172554',edge:'#93c5fd',glow:.34},Advanced:{color:'#8b5cf6',deep:'#3b0764',edge:'#c4b5fd',glow:.43},Elite:{color:'#22d3ee',deep:'#082f49',edge:'#cffafe',glow:.58}};
const neutral={color:'#334155',deep:'#0f172a',edge:'#64748b',glow:.08};
export default function BodyMap({rating,view='front',compact=false,selected,onSelect}){
  const uid=useId().replace(/:/g,''),body=`body-${uid}`,aura=`aura-${uid}`,clip=`clip-${uid}`,glow=`glow-${uid}`,scan=`scan-${uid}`;
  const stateFor=muscle=>rating?.hasData?(tiers[rating?.muscles?.[muscle]?.level]||tiers.Beginner):neutral;
  return <svg viewBox={BODY_VIEW_BOX} preserveAspectRatio="xMidYMid meet" className={compact?'h-40 w-16':'mx-auto h-[430px] w-60 max-w-full'} aria-label={`${view} athletic muscle rating map`}>
    <defs><radialGradient id={aura}><stop stopColor="hsl(var(--primary))" stopOpacity=".3"/><stop offset="1" stopColor="hsl(var(--primary))" stopOpacity="0"/></radialGradient><linearGradient id={body} x1="0" y1="0" x2="1" y2="1"><stop stopColor="hsl(var(--foreground))" stopOpacity=".22"/><stop offset=".28" stopColor="hsl(var(--card))"/><stop offset=".7" stopColor="hsl(var(--secondary))"/><stop offset="1" stopColor="hsl(var(--background))"/></linearGradient><linearGradient id={scan} x1="0" y1="0" x2="1" y2="0"><stop stopColor="hsl(var(--primary))" stopOpacity="0"/><stop offset=".5" stopColor="hsl(var(--primary))" stopOpacity=".3"/><stop offset="1" stopColor="hsl(var(--primary))" stopOpacity="0"/></linearGradient><clipPath id={clip}><path d={silhouette[view]}/></clipPath><filter id={glow} x="-60%" y="-60%" width="220%" height="220%"><feGaussianBlur stdDeviation={compact?'2':'3.8'}/></filter>{regions[view].map(([muscle,,path],index)=>{const state=stateFor(muscle);return <linearGradient key={index} id={`muscle-${uid}-${index}`} x1="0" y1="0" x2="1" y2="1"><stop stopColor={state.edge}/><stop offset=".38" stopColor={state.color}/><stop offset="1" stopColor={state.deep}/></linearGradient>})}</defs>
    {!compact&&<><ellipse className="limit-aura" cx="100" cy="220" rx="88" ry="205" fill={`url(#${aura})`}/><path d="M18 80H5M18 130H10M18 180H5M182 80H195M182 130H190M182 180H195" stroke="hsl(var(--primary))" strokeOpacity=".24" strokeWidth=".8"/></>}
    <path d={headPath} fill={`url(#${body})`} stroke="hsl(var(--foreground))" strokeOpacity=".38" strokeWidth="1.15"/><path d={silhouette[view]} fill={`url(#${body})`} stroke="hsl(var(--foreground))" strokeOpacity=".42" strokeWidth="1.35"/>
    <g clipPath={`url(#${clip})`}>{regions[view].map(([muscle,label,path],index)=>{const state=stateFor(muscle),active=selected===muscle,opacity=active?1:(rating?.hasData ? .78 : .5);return <Fragment key={`${label}-${index}`}><path d={path} fill={state.color} opacity={active?state.glow:.1} filter={`url(#${glow})`} pointerEvents="none"/><path d={path} fill={`url(#muscle-${uid}-${index})`} fillOpacity={opacity} stroke={state.edge} strokeOpacity={active?1:.46} strokeWidth={active?1.7:.65} vectorEffect="non-scaling-stroke" role="button" tabIndex="0" aria-label={`${label}: ${rating?.muscles?.[muscle]?.level||'Calibrating'}`} onClick={()=>onSelect?.(muscle)} onKeyDown={event=>['Enter',' '].includes(event.key)&&onSelect?.(muscle)} className="cursor-pointer transition-opacity duration-300"/></Fragment>})}<path d={detailLines[view]} fill="none" stroke="hsl(var(--foreground))" strokeOpacity=".18" strokeWidth=".72" pointerEvents="none"/>{!compact&&<rect className="body-scan-line" x="12" y="0" width="176" height="2" fill={`url(#${scan})`} pointerEvents="none"/>}</g>
    <path d={silhouette[view]} fill="none" stroke="hsl(var(--foreground))" strokeOpacity=".48" strokeWidth="1.15" pointerEvents="none"/><path d="M90 50Q100 58 110 50M92 24Q100 19 108 24M95 38Q100 42 105 38" fill="none" stroke="hsl(var(--foreground))" strokeOpacity=".18" strokeWidth=".65" pointerEvents="none"/>
  </svg>;
}