import { readFileSync, writeFileSync } from "node:fs";
const rows = JSON.parse(readFileSync("media/manifest.json"));
const escape = (s) =>
  s.replace(
    /[&<>"']/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]
  );
const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>LIMIT movement review</title><style>body{background:#080d18;color:#edf2fc;font:16px system-ui;margin:24px}header{max-width:900px}input,textarea,button{font:inherit;padding:12px;margin:8px 0}article{border:1px solid #425873;border-radius:16px;padding:16px;margin:20px 0;max-width:960px}video,img{width:100%;max-width:640px}label{display:block}textarea{width:80%}button{cursor:pointer}a{color:#73acff}</style><header><h1>LIMIT movement review</h1><p>Inspect each exact movement and its equipment, start, range and return. Technical checks are not human fitness approval. Approve only movements you actually reviewed and are qualified to assess. Blocked entries need a faithful new template before approval.</p><label>Reviewer name <input id="reviewer" required></label><label>Filter exercises <input id="search" type="search"></label><button id="export">Export checked review decisions</button><p id="status" role="status"></p></header>${rows.map((r) => `<article data-key="${r.catalogKey}" data-checksum="${r.videoSha256 || ""}"><h2>${escape(r.name)}</h2><p>${escape(r.reviewStatus)} · ${r.catalogKey}</p>${r.source ? `<video controls preload="none" poster="${r.catalogKey}/poster.png" src="${r.catalogKey}/movement.mp4"></video>` : `<img loading="lazy" alt="Written guide for ${escape(r.name)}" src="${r.catalogKey}/poster.png"><p>${escape(r.blockReason)}</p>`}<p>${escape(r.caption)}</p>${r.source ? '<label><input type="checkbox" class="inspected"> I inspected this exact video</label><label>Decision <select><option value="reject">Needs changes</option><option value="approve">Approve movement</option></select></label><label>Review evidence and observations<textarea placeholder="Describe the setup, joint path, equipment and any corrections"></textarea></label>' : ""}</article>`).join("")}<script>document.querySelector('#search').oninput=e=>document.querySelectorAll('article').forEach(a=>a.hidden=!a.textContent.toLowerCase().includes(e.target.value.toLowerCase()));document.querySelector('#export').onclick=()=>{const reviewer=document.querySelector('#reviewer').value.trim();const decisions=[...document.querySelectorAll('article')].filter(a=>a.querySelector('.inspected')?.checked).map(a=>({catalogKey:a.dataset.key,videoSha256:a.dataset.checksum,decision:a.querySelector('select').value,notes:a.querySelector('textarea').value.trim()}));if(!reviewer||!decisions.length||decisions.some(d=>d.notes.length<20)){document.querySelector('#status').textContent='Enter your name, inspect videos, and record at least 20 characters of evidence for each decision.';return;}const data={reviewer,reviewedAt:new Date().toISOString(),decisions};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='limit-human-review.json';a.click();URL.revokeObjectURL(a.href);};</script></html>`;
writeFileSync("media-output/review.html", html);
console.log(
  "Serve media-output on localhost and open review.html. Nothing is approved automatically."
);
